name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hola mundo"
      - name: Print goodbye
        run: echo "Listo - chao!"
      - name: Print multiple lines
        run: |
          echo "Primer output"
          echo "Segundo output"
